import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs';
import Navbar from '@/components/Navbar';
import {cn} from "@/lib/utils";

const font = Montserrat({ 
  subsets: ['latin'],
  weight: ['400'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={cn(font.className, "min-h-screen")}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
